#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define LEVEL_WIDTH 1280
#define LEVLEL_HEIGHT 720

#define ENTITY_SCALE 4
#define PLAYER_SCALE 3

#define PLAYER_FRAMES 4
#define PLAYER_FRAME_DELAYED 8

#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define TILES_TOTAL ((SCREEN_WIDTH - 20) / ENTITY_SCALE) / TILE_WIDTH

#define DEBUG 0