#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define LEVEL_WIDTH 1280
#define LEVLEL_HEIGHT 720

#define ENTITY_SCALE 4

#define PLAYER_FRAMES 4
#define PLAYER_FRAME_DELAYED 8

#define TILE_WIDTH 30
#define TILE_HEIGHT 30
#define TILES_TOTAL ((SCREEN_WIDTH - 20) / ENTITY_SCALE) / TILE_WIDTH
